declare namespace NodeJS {
  interface ProcessEnv {
    NEXT_PUBLIC_CHANNEL_IO_KEY: string;
    NEXT_PUBLIC_SERVER_URL: string;
    NEXT_PUBLIC_CLIENT_URL: string;
    NEXT_PUBLIC_S3_URL: string;
    NEXT_PUBLIC_COOKIE_DOMAIN: string;

    NEXT_PUBLIC_PORTONE_STORE_ID: string;
    NEXT_PUBLIC_PORTONE_API_SECRET: string;
    NEXT_PUBLIC_PORTONE_CHANNEL_KEY: string;

    NEXT_PUBLIC_KAKAO_API_KEY: string;
    NEXT_PUBLIC_KAKAO_REDIRECT_URI: string;
    NEXT_PUBLIC_KAKAO_JS_KEY: string;

    NEXT_PUBLIC_MEMBERSHIP_DISABLED: string;

    NEXT_PUBLIC_GOOGLE_ANALYTICS: string;
  }
}
