const API_CODE = {
  success: 'SUCCESS',
  unexpected: 'UNEXPECTED_ERROR',
  storeDetail: {
    notFound: 'PRODUCT_NOT_FOUND',
  },
  ACCESS_TOKEN_FAILURE: 'ACCESS_TOKEN_FAILURE',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
};

export default API_CODE;
