export const FILE_TYPES = [
  { label: 'PSD', value: 'PSD' },
  { label: 'AI', value: 'AI' },
  { label: 'PNG', value: 'PNG' },
  { label: 'JPG', value: 'JPG' },
  { label: 'MP4', value: 'MP4' },
  { label: 'GIF', value: 'GIF' },
  { label: 'PDF', value: 'PDF' },
  { label: 'SVG', value: 'SVG' },
  { label: 'TIFF', value: 'TIFF' },
  { label: 'MOV', value: 'MOV' },
  { label: 'AVI', value: 'AVI' },
  { label: 'WMV', value: 'WMV' },
  { label: 'MKV', value: 'MKV' },
  { label: 'Blender', value: 'BLENDER' },
  { label: 'Unity', value: 'UNITY' },
  { label: 'VRM', value: 'VRM' },
  { label: 'VRF', value: 'VRF' },
  { label: 'MAX', value: 'MAX' },
  { label: 'GLTF/GLB', value: 'GLTF_GLB' },
  { label: 'OBJ', value: 'OBJ' },
  { label: 'VSF', value: 'VSF' },
];
